Rs 74 admin panel for system management
raji2004/RefreeG-Platform pull request #7
Opened 2024-10-06 12:07 UTC by nomsou

2024-10-06 13:41 UTC, raji2004 commented
Error: Can't parse json file /vercel/path0/package.json: Expected double-quoted property name in JSON at position 230 while parsing '{
  "name": "refreeg",
  "version": "0.1'



The deployment failed due to this error fix it

2024-10-06 13:46 UTC, nomsou commented
Alright, will do!

On Sun, Oct 6, 2024, 2:41 PM Raji Muhammad Muzzamil <
***@***.***> wrote:

> Error: Can't parse json file /vercel/path0/package.json: Expected
> double-quoted property name in JSON at position 230 while parsing '{
> "name": "refreeg",
> "version": "0.1'
>
> The deployment failed due to this error fix it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/raji2004/RefreeG-Platform/pull/7#issuecomment-2395444915>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWPT3UT2M73QFWJBZQVEWBTZ2E4YLAVCNFSM6AAAAABPOIOK3OVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGQ2DIOJRGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-10 09:18 UTC, raji2004 requested changes
put your test in the test folder

2024-10-10 10:02 UTC, raji2004 approved these changes

2024-10-10 10:09 UTC, merged